const path = require('path');

const services = [
  { name: 'codesprout-gateway',   script: 'dist/services/gateway.js',   port: 3000 },
  { name: 'codesprout-auth',      script: 'dist/services/auth.js',      port: 3001 },
  { name: 'codesprout-content',   script: 'dist/services/content.js',   port: 3002 },
  { name: 'codesprout-social',    script: 'dist/services/social.js',    port: 3003 },
  { name: 'codesprout-execution', script: 'dist/services/execution.js', port: 3004 },
  { name: 'codesprout-payment',   script: 'dist/services/payment.js',   port: 3005 },
  { name: 'codesprout-resume',    script: 'dist/services/resume.js',    port: 3006 },
];

module.exports = {
  apps: services.map((s) => ({
    name: s.name,
    script: path.join(__dirname, s.script),
    cwd: __dirname,
    instances: 1,
    exec_mode: 'fork',
    autorestart: true,
    restart_delay: 2000,
    max_restarts: 20,
    min_uptime: '30s',
    max_memory_restart: '512M',
    kill_timeout: 8000,
    listen_timeout: 15000,
    env: {
      NODE_ENV: 'production',
      PORT: String(s.port),
      JWT_SECRET: process.env.JWT_SECRET || '',
      ENCRYPTION_KEY: process.env.ENCRYPTION_KEY || '',
      MONGODB_URL: process.env.MONGODB_URL || '',
      RAZORPAY_KEY_ID: process.env.RAZORPAY_KEY_ID || '',
      RAZORPAY_KEY_SECRET: process.env.RAZORPAY_KEY_SECRET || '',
      RAZORPAY_WEBHOOK_SECRET: process.env.RAZORPAY_WEBHOOK_SECRET || '',
      SMTP_HOST: process.env.SMTP_HOST || 'smtp.gmail.com',
      SMTP_PORT: process.env.SMTP_PORT || '587',
      SMTP_USER: process.env.SMTP_USER || '',
      SMTP_PASS: process.env.SMTP_PASS || '',
      EMAIL_FROM: process.env.EMAIL_FROM || '',
      FRONTEND_URL: process.env.FRONTEND_URL || '',
      OPENROUTER_API_KEY: process.env.OPENROUTER_API_KEY || '',
      UPI_ID: process.env.UPI_ID || '',
      UPI_PAYEE_NAME: process.env.UPI_PAYEE_NAME || 'CodeSprout',
      PREMIUM_AMOUNT: process.env.PREMIUM_AMOUNT || '49',
      SUBSCRIPTION_DAYS: process.env.SUBSCRIPTION_DAYS || '30',
      GEMINI_API_KEY: process.env.GEMINI_API_KEY || '',
      AUTH_SERVICE_URL: process.env.AUTH_SERVICE_URL || 'http://127.0.0.1:3001',
      CONTENT_SERVICE_URL: process.env.CONTENT_SERVICE_URL || 'http://127.0.0.1:3002',
      SOCIAL_SERVICE_URL: process.env.SOCIAL_SERVICE_URL || 'http://127.0.0.1:3003',
      EXECUTION_SERVICE_URL: process.env.EXECUTION_SERVICE_URL || 'http://127.0.0.1:3004',
      PAYMENT_SERVICE_URL: process.env.PAYMENT_SERVICE_URL || 'http://127.0.0.1:3005',
      RESUME_SERVICE_URL: process.env.RESUME_SERVICE_URL || 'http://127.0.0.1:3006',
    },
  })),
};
